apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: Y2EuY2VydAo= # Base64 encoded "ca.crt"
    server: https://1.2.3.4
  name: clustername-gke
- cluster:
    certificate-authority: ca.crt
    server: https://192.168.0.177:8443
  name: clustername-minikube
- cluster:
    certificate-authority-data: Y2EuY2VydAo= # Base64 encoded "ca.crt"
    server: https://5.6.7.8
  name: clustername-eks
contexts:
- context:
    cluster: clustername-eks
    user: aws
  name: eks
- context:
    cluster: clustername-gke
    user: gke_foo-bar-123456_australia-southeast1-foobar
  name: gke
- context:
    cluster: clustername-minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: gke_foo-bar-123456_australia-southeast1-foobar
  user:
    auth-provider:
      config:
        access-token: encrypted-access-token
        cmd-args: config config-helper --format=json
        cmd-path: /usr/bin/gcloud
        expiry: 2019-01-14T02:48:51Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - eks-cluster-name
      command: aws-iam-authenticator
      env:
        - name: foo1
          value: bar1
        - name: foo2
          value: bar2
- name: minikube
  user:
    client-certificate: client.crt
    client-key: client.key
