apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: encrypted-authority-data
    server: https://1.2.3.4
  name: gke_foo-bar-123456_australia-southeast1-foobar
- cluster:
    certificate-authority: ca.crt
    server: https://192.168.0.177:8443
  name: minikube
contexts:
- context:
    cluster: gke_foo-bar-123456_australia-southeast1-foobar
    user: gke_foo-bar-123456_australia-southeast1-foobar
  name: gke
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: gke_foo-bar-123456_australia-southeast1-foobar
  user:
    auth-provider:
      config:
        access-token: encrypted-access-token
        cmd-args: config config-helper --format=json
        cmd-path: /usr/bin/gcloud
        expiry: 2019-01-14T02:48:51Z
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: minikube
  user:
    client-certificate: client.crt
    client-key: client.key
