# ------------------------------------------------------------------------------
# Base image to build packages with PyInstaller.
#
# We use an older version of Ubuntu to ensure its GLIBC is compatible# with all
# reasonable recent Linux distributions.
# ------------------------------------------------------------------------------
FROM ubuntu:16.04

# Select the Python version.
ARG PYTHONVERSION=3.7.7

RUN apt update && apt upgrade -y
RUN apt install -y wget \
  build-essential \
  git \
  libssl-dev zlib1g-dev \
  libncurses5-dev \
  libncursesw5-dev \
  libreadline-dev \
  libsqlite3-dev\
  libgdbm-dev \
  libdb5.3-dev \
  libbz2-dev \
  libexpat1-dev \
  liblzma-dev \
  libffi-dev \
  uuid-dev

# Download and build Python.
RUN wget https://www.python.org/ftp/python/$PYTHONVERSION/Python-$PYTHONVERSION.tgz
RUN tar -xzvf Python-$PYTHONVERSION.tgz \
  && cd Python-$PYTHONVERSION \
  && ./configure --enable-shared --prefix=/usr/local LDFLAGS="-Wl,--rpath=/usr/local/lib" \
  && make -j8 \
  && make install

# Upgrade to latest PIP.
RUN pip3 install --upgrade pip
RUN pip3 install pipenv
