apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: square-1
  labels:
    app: demoapp-1
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get", "list", "update", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: square-1
  labels:
    app: demoapp-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: square-1
subjects:
- kind: ServiceAccount
  name: square-1
  namespace: square
