# Square configuration syntax.
version: v1.0

# Kubernetes credentials.
kubeconfig: /path/to/kubeconfig
kubecontext: null

# Where Square will read and write manifests.
folder: manifests/


# -----------------------------------------------------------------------------
# Connection Parameters.
# -----------------------------------------------------------------------------
connection_parameters:
  # Disable strict SSL certificate checks for cluster. This is only recommended
  # if the control plane of your cluster was created a few years ago. See this
  # link for more info: https://github.com/aws/containers-roadmap/issues/2638
  disable_x509_strict: false

  # Extra headers to pass along to the K8s API with every call.
  k8s_extra_headers:
    foo: bar


# -----------------------------------------------------------------------------
# Square will only target resources that match *all* the selectors below.
# -----------------------------------------------------------------------------
selectors:
  # - Capitalisation, singular/plural is irrelevant (role, roles, ROLE are equivalent).
  # - Use explicit groups to avoid ambiguity (`deployment.apps` instead of `deployment`).
  # - Abbreviations work: {svc, service, services, svc.v1, service.v1}.
  # - Target specific resources: `svc.v1/name`. Prefer `labels` below if possible.
  kinds:
    - clusterrole
    - clusterrolebinding
    - configmap
    - customresourcedefinition
    - deployment.apps
    - horizontalpodautoscaler.autoscaling
    - ingress.networking.k8s.io
    - namespace
    - role
    - rolebinding
    - service
    - serviceaccount

  # target these namespaces. Use an empty list to target all.
  namespaces: []

  # Example: ["app=square", "foo=bar"]. Use an empty list to ignore labels.
  labels: []


# -----------------------------------------------------------------------------
# Define the folder hierarchy that `square get` should create.
# -----------------------------------------------------------------------------
groupby:
  label: app
  order: [ns, label, kind]


# -----------------------------------------------------------------------------
# Square will create resources in this order, and delete them in reverse order.
# This list need not be complete. Square will treat all unlisted resource as
# if they had been added at the end of that list.
# -----------------------------------------------------------------------------
priorities:
  # Custom resources come first.
  - customresourcedefinition

  # Common non-namespaced resources.
  - clusterrole
  - clusterrolebinding

  # Namespaces must come before any namespaced resources.
  - namespace

  # RBAC.
  - role
  - rolebinding
  - serviceaccount

  # Everything else.
  - configmap
  - service
  - deployment.apps
  - horizontalpodautoscaler.autoscaling
  - ingress.networking.k8s.io


# -----------------------------------------------------------------------------
# Square will omit all manifest keys defined here in its plan and patches. It
# will also skip those keys if it creates a new resource.
# -----------------------------------------------------------------------------
filters:
  # --- These will be inserted into all resource types to reduce boiler plate. ---
  _common_:
    - metadata.annotations["autoscaling.alpha.kubernetes.io/conditions"]
    - metadata.annotations["deployment.kubernetes.io/revision"]
    - metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]
    - metadata.annotations["kubernetes.io/change-cause"]
    - metadata.creationTimestamp
    - metadata.generation
    - metadata.managedFields
    - metadata.resourceVersion
    - metadata.selfLink
    - metadata.uid
    - status

  # --- Individual resource types. ---
  configmap:
    - metadata.annotations

  deployment.apps: []

  horizontalpodautoscaler.autoscaling:
    - metadata.annotations["autoscaling.alpha.kubernetes.io/conditions"]
    - metadata.annotations["autoscaling.alpha.kubernetes.io/current-metrics"]
    - metadata.annotations["control-plane.alpha.kubernetes.io/leader"]

  service:
    - spec.clusterIP
    - spec.ports[*].nodePort
    - spec.sessionAffinity
