name: Square

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pyinstaller
          pipenv install --system --deploy --dev
      - name: Run Unit Tests
        run: |
          pytest --cov=square
      - name: Build Binary
        run: |
          pyinstaller -n square square/__main__.py
          pyinstaller --noconfirm square.spec --onefile

  build-linux-docker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build artifact inside Docker image
        run: |
          docker build -t "builder:latest" -f Dockerfile .
          docker create -ti --rm --name tmp builder
          docker cp tmp:/src/square/dist/square/square ./square
          docker rm tmp
      - name: create-artifact
        uses: actions/upload-artifact@v2
        with:
          name: square-linux
          path: square

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pyinstaller macholib pypiwin32 atomicwrites
          pipenv install --system --deploy --dev
      - name: Run Unit Tests
        run: |
          pytest --cov=square --ignore=tests/test_integration.py
      - name: Build Binary
        run: |
          pyinstaller -n square square/__main__.py
          pyinstaller --noconfirm square.spec --onefile
      - name: create-artifact
        uses: actions/upload-artifact@v2
        with:
          name: square-windows
          path: dist/square/square.exe


  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pyinstaller
          pipenv install --system --deploy --dev
      - name: Run Unit Tests
        run: |
          pytest --cov=square
      - name: Build Binary
        run: |
          pyinstaller -n square square/__main__.py
          pyinstaller --noconfirm square.spec --onefile
      - name: create-artifact
        uses: actions/upload-artifact@v2
        with:
          name: square-macos
          path: dist/square/square
